import "./globals.css";
import type { Metadata } from "next";
import { Rubik, Geist, Geist_Mono } from "next/font/google";

import {Menubar, MenubarContent, MenubarItem, MenubarMenu, MenubarSeparator, MenubarShortcut, MenubarTrigger} from '@/components/ui/menubar'
import Navbar from "@/components/shared/Navbar";
import { Sidebar } from "lucide-react";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/ui/app-sidebar"

const rubik = Rubik({subsets: ['latin']})

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <body className={`${rubik}`}
        /* className={`${geistSans.variable} ${geistMono.variable} antialiased`} */
      >
        <Navbar />
        {children}

        {/* 
        <SidebarProvider>
          <AppSidebar />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
        {children} */}
        <div className="flex">
            
          {/* <SidebarProvider>
            <AppSidebar />
            <main>
              <SidebarTrigger />
            </main>
          </SidebarProvider> */}
          {/* <div className=" w-full">
          </div> */}
        </div>
      </body>
    </html>
  );
}
